site_name: MlOre
site_url: https://shukla007.github.io/MLore/
repo_url: https://github.com/shukla007/MLOre
repo_name: shukla007/MLOre

theme:
  name: material
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: light blue
      accent: dark blue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: light blue
      accent: dark blue

plugins:
  - social:
      enabled: !ENV [CI, false]
  - search
  

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/shukla007
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/avi0_07
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/abhishekshukla007/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - tables
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/shukla007"  target="_blank" rel="noopener">Abhishek Shukla</a>